#!/bin/bash
# Builds PowerpointViewer.app — a double-clickable macOS application bundle.
set -euo pipefail

CONFIG="release"
APP_NAME="PowerpointViewer"
DISPLAY_NAME="PowerPoint Viewer"
BUNDLE_ID="com.example.powerpointviewer"
BUILD_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$BUILD_DIR/$APP_NAME.app"

echo "▶ Building ($CONFIG)…"
swift build -c "$CONFIG"

BIN_PATH="$(swift build -c "$CONFIG" --show-bin-path)/$APP_NAME"

echo "▶ Assembling bundle…"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

cp "$BIN_PATH" "$APP_DIR/Contents/MacOS/$APP_NAME"

# App icon (optional — generated by Tools/generate_icon.swift).
ICON_SRC="$BUILD_DIR/Tools/AppIcon.icns"
ICON_KEY=""
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$APP_DIR/Contents/Resources/AppIcon.icns"
    ICON_KEY="    <key>CFBundleIconFile</key>        <string>AppIcon</string>"
fi

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>$DISPLAY_NAME</string>
    <key>CFBundleDisplayName</key>     <string>$DISPLAY_NAME</string>
    <key>CFBundleExecutable</key>      <string>$APP_NAME</string>
$ICON_KEY
    <key>CFBundleIdentifier</key>      <string>$BUNDLE_ID</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleShortVersionString</key> <string>1.0</string>
    <key>CFBundleVersion</key>         <string>1</string>
    <key>LSMinimumSystemVersion</key>  <string>14.0</string>
    <key>NSHighResolutionCapable</key> <true/>
    <key>NSPrincipalClass</key>        <string>NSApplication</string>
    <key>NSCameraUsageDescription</key>
    <string>Shows a live camera preview in the presenter console.</string>
    <key>CFBundleDocumentTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeName</key>     <string>PowerPoint Presentation</string>
            <key>CFBundleTypeRole</key>     <string>Viewer</string>
            <key>LSHandlerRank</key>        <string>Alternate</string>
            <key>LSItemContentTypes</key>
            <array>
                <string>org.openxmlformats.presentationml.presentation</string>
            </array>
        </dict>
    </array>
</dict>
</plist>
PLIST

# Ad-hoc code signature so Gatekeeper lets it launch locally.
codesign --force --deep --sign - "$APP_DIR" 2>/dev/null || true

echo "✓ Built $APP_DIR"
echo "  Run with: open \"$APP_DIR\""
